version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ./rabbitmq-disk/data/:/var/lib/rabbitmq/
        - ./rabbitmq-disk/log/:/var/log/rabbitmq

  #flower:  
  #  image: mher/flower
  #  command: ["flower", "--broker=amqp://guest:guest@localhost:5672//", "--port=5555"] 
  #  depends_on:
  #    - rabbitmq
  #  ports:
  #     - 5555:5555 