server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push


scrape_configs:
- job_name: springboot
  pipeline_stages:
  - json:
      expressions:
        level: level
        message: message
        timestamp: timestamp
        scheduler_id: scheduler_id
        status: status
        result: result
  - labels:
      level:
      scheduler_id:
      status:

  static_configs:
  - targets:
      - localhost
    labels:
      job: applogs
      __path__: /logs/*.json