version: "3"
services:
  www-api:
    network_mode: "host"
    restart: always
    build:
      args: 
        - ENVIRONMENT=development
      context: .
      dockerfile: Dockerfile.dev
    #ports:
    #  - 3030:3030
    environment:
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
    env_file:
      - ./.env
    volumes:
      - ./:/opt/app
