# Generated by Django 3.2.3 on 2021-05-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcesmodel",
            name="reference_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
