# ./config/auth0.yml
development:
  auth0_domain: <%= ENV.fetch("AUTH0_WWW_DOMAIN") { "" } %>
  auth0_client_id: <%= ENV.fetch("AUTH0_WWW_CLIENT_ID") { "" } %>
  auth0_client_secret: <%= ENV.fetch("AUTH0_WWW_CLIENT_SECRET") { "" } %>

test:
  auth0_domain: <%= ENV.fetch("AUTH0_WWW_DOMAIN") { "" } %>
  auth0_client_id: <%= ENV.fetch("AUTH0_WWW_CLIENT_ID") { "" } %>
  auth0_client_secret: <%= ENV.fetch("AUTH0_WWW_CLIENT_SECRET") { "" } %>

production:
  auth0_domain: <%= ENV.fetch("AUTH0_WWW_DOMAIN") { "" } %>
  auth0_client_id: <%= ENV.fetch("AUTH0_WWW_CLIENT_ID") { "" } %>
  auth0_client_secret: <%= ENV.fetch("AUTH0_WWW_CLIENT_SECRET") { "" } %>