name: Deploy

on:
  push:
    branches:
      - master

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: deploy
        env:
          FERNET_SECRET_KEY: ${{secrets.FERNET_SECRET_KEY_TEST}}
          MAIN_SERVER_SSH_B64: ${{secrets.MAIN_SERVER_SSH_B64}}
          MAIN_SERVER_HOST: ${{secrets.MAIN_SERVER_HOST}}
          MAIN_SERVER_USERNAME: ${{secrets.MAIN_SERVER_USERNAME}}
          GRAFANA_DOTENV: ${{secrets.GRAFANA_DOTENV}}
          DOTENV_WWW_PROD: ${{secrets.DOTENV_WWW_PROD}}
        run: |

          # .env
          echo "FERNET_SECRET_KEY=$FERNET_SECRET_KEY" > .env
          echo "PYTHONUNBUFFERED=1" >> .env

          # .env for www-cronrobot
          echo "$DOTENV_WWW_PROD" | base64 -d > .www-cronrobot.env

          # .grafana.env
          echo "$GRAFANA_DOTENV" | base64 -d > .grafana.env

          # ssh setup
          mkdir .ssh
          echo $MAIN_SERVER_SSH_B64 | base64 -d > .ssh/main_server_pk
          chmod 400 .ssh/main_server_pk
          ssh_in="ssh -o StrictHostKeyChecking=no -i .ssh/main_server_pk $MAIN_SERVER_USERNAME@$MAIN_SERVER_HOST"

          # git pull
          go_home="cd /var/www/cronrobot"
          $ssh_in "$go_home ; git pull"
          cat .env | $ssh_in -T "cat > /var/www/cronrobot/.env"
          cat .grafana.env | $ssh_in -T "cat > /var/www/cronrobot/.grafana.env"
          cat .www-cronrobot.env | $ssh_in -T "cat > /var/www/cronrobot/www-cronrobot/.env"

          # python deps
          $ssh_in "cd /var/www/cronrobot/celery-admin ; pip install -r requirements.txt"

          $ssh_in "$go_home ; sudo docker-compose build"
          $ssh_in "$go_home ; sudo docker-compose up -d"
