name: Deploy

on:
  push:
    branches:
      - master

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: git pull
        env:
          FERNET_SECRET_KEY: ${{secrets.FERNET_SECRET_KEY_TEST}}
          MAIN_SERVER_SSH_B64: ${{secrets.MAIN_SERVER_SSH_B64}}
          MAIN_SERVER_HOST: ${{secrets.MAIN_SERVER_HOST}}
          MAIN_SERVER_USERNAME: ${{secrets.MAIN_SERVER_USERNAME}}
        run: |
          mkdir .ssh
          echo $MAIN_SERVER_SSH_B64 | base64 -d > .ssh/main_server_pk
          chmod 400 .ssh/main_server_pk
          ssh_in="ssh -o StrictHostKeyChecking=no -i .ssh/main_server_pk $MAIN_SERVER_USERNAME@$MAIN_SERVER_HOST"
          go_home="cd /var/www/cronrobot"
          $ssh_in "$go_home ; git pull"

